[project]
name = "target-adbc"
dynamic = ["version"]
description = "Singer target for loading data into ADBC-compatible databases"
licence = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "singer-sdk~=0.53.5",
    "adbc-driver-manager>=1.9.0",
    "pyarrow>=22.0.0",
    "duckdb>=1.4.1",
]
optional-dependencies.duckdb = ["duckdb>=1.4.1"]

[project.scripts]
target-adbc = "target_adbc.target:TargetADBC.cli"

[dependency-groups]
dev = [
    "coverage>=7.11.3",
    "mypy>=1.18.0",
    "pyarrow-stubs>=20.0.0.20251107",
    "pytest>=9.0.0",
    "ruff>=0.14.0",
    "target-adbc[duckdb]",
    "ty>=0.0.1a25",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
fallback-version = "0.1.0dev0"
source = "vcs"

[tool.pytest]
addopts = ["-v", "-ra", "--strict-config", "--strict-markers"]
filterwarnings = ["error"]
log_level = "INFO"
minversion = "9"
testpaths = ["tests"]
xfail_strict = true

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = [
    "S",    # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    "B",    # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "RSE",  # https://docs.astral.sh/ruff/rules/#flake8-raise-rse
    "RET",  # https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "SLF",  # https://docs.astral.sh/ruff/rules/#flake8-self-slf
    "SIM",  # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "TC",   # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tc
    "I",    # https://docs.astral.sh/ruff/rules/#isort-i
    "UP",   # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "FURB", # https://docs.astral.sh/ruff/rules/#refurb-furb
    "RUF",  # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = [
    "S101",  # pytest uses assert statements
    "S608",  # Raw SQL queries are OK in tests
]

[tool.mypy]
check_untyped_defs = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
strict = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true

[tool.uv]
no-build-package = ["jsonpath-ng"]
