[project]
name = "target-adbc"
dynamic = ["version"]
description = "Singer target for loading data into ADBC-compatible databases"
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "singer-sdk~=0.54.2",
    "adbc-driver-manager~=1.11.0",
    "pyarrow~=24.0",
    "typing-extensions>=4.15.0 ; python_full_version < '3.12'",
]

[project.scripts]
target-adbc = "target_adbc.target:TargetADBC.cli"

[dependency-groups]
dev = [
    "coverage>=7.14",
    "duckdb>=1.5.3",
    "mypy>=1.18.0",
    "pyarrow-stubs>=20.0.0.20251107",
    "pytest>=9.0.0",
    "ruff>=0.14.0",
    "testcontainers[mssql,postgres]>=4.14",
    "ty>=0.0.1a25",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
fallback-version = "0.1.0dev0"
source = "vcs"

[tool.pytest]
addopts = ["-v", "-ra"]
filterwarnings = [
    "error",
    "once:The @wait_container_is_ready decorator is deprecated and will be removed in a future version:DeprecationWarning",
]
log_level = "INFO"
minversion = "9"
strict = true
testpaths = ["tests"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = [
    "ERA",  # https://docs.astral.sh/ruff/rules/#eradicate-era
    "ANN",  # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    "S",    # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    "B",    # https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "RSE",  # https://docs.astral.sh/ruff/rules/#flake8-raise-rse
    "RET",  # https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "SLF",  # https://docs.astral.sh/ruff/rules/#flake8-self-slf
    "SIM",  # https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
    "TC",   # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tc
    "FLY",  # https://docs.astral.sh/ruff/rules/#flynt-fly
    "I",    # https://docs.astral.sh/ruff/rules/#isort-i
    "C90",  # https://docs.astral.sh/ruff/rules/#mccabe-c90
    "PERF", # https://docs.astral.sh/ruff/rules/#perflint-perf
    "PL",   # https://docs.astral.sh/ruff/rules/#pylint-pl
    "UP",   # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "FURB", # https://docs.astral.sh/ruff/rules/#refurb-furb
    "RUF",  # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**/*.py" = [
    "ANN401",  # Any is fine for fixture / test parameter types
    "PLR2004", # Magic value is fine in tests
    "S101",    # pytest uses assert statements
    "S608",    # Raw SQL queries are OK in tests
]

[tool.mypy]
check_untyped_defs = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
follow_untyped_imports = true
strict = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true
