name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.12"
        - "3.13"
        - "3.14"
        drivers_source:
        - pypi
        - dbc
        os:
        - ubuntu-latest
        include:
        - python-version: 3.14
          drivers_source: pypi
          os: windows-latest
        - python-version: 3.14
          drivers_source: dbc
          os: windows-latest
        - python-version: 3.14
          drivers_source: pypi
          os: macos-latest
        - python-version: 3.14
          drivers_source: dbc
          os: macos-latest

    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6-beta
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          cache-suffix: ${{ matrix.drivers_source }}
          python-version: ${{ matrix.python-version }}

      - name: Install drivers with no PyPI package
        run: uvx dbc sync --path required.dbc.toml

      - name: Install remaining ADBC drivers with dbc
        if: ${{ matrix.drivers_source == 'dbc' }}
        run: uvx dbc sync --path all.dbc.toml

      - name: Run tests
        if: ${{ matrix.drivers_source == 'dbc' }}
        env:
          TOXENV: ${{ case(matrix.drivers_source == 'dbc', 'dbc', matrix.python-version) }}
        run: uvx --with tox-uv tox -- -v

  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e # v6-beta
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          cache-suffix: lint

      - name: Tox
        run: uvx --with tox-uv tox -e lint
